#!/bin/bash

for git_user in ${GIT_USERS//,/ }; do 
  gitreceive init "$git_user"
  for github_user in ${GITHUB_USERS//,/ }; do 
    /armada/gitreceive add-github-user "$git_user" "$github_user"
  done
done

#if [ "$USE_DIND" == "true" ]; then
#  dind
#fi

# Pass select variariables into the global environment
declare|grep -E '^(DOCKER_HOST)=' >> /etc/environment

echo "Starting SSH..."
exec /usr/sbin/sshd -D -e

