#!/bin/bash

echo "Processing git receive"
# this script path
ARMADA_DIR=$(realpath $(dirname $0))

. "$ARMADA_DIR/functions"

repository=$1
branch=$2
revision=$3
username=$4
fingerprint=$5

assert repository
assert branch
assert revision
assert username
assert fingerprint

namespace=$(echo $repository | cut -d/ -f1)

echo " * namespace=$namespace"
echo " * repository=$repository"
echo " * branch=$branch"
echo " * revision=$revision"
echo " * username=$username"
echo " * fingerprint=$fingerprint"

include expander
include builder
include deployer

clean
